#!/usr/bin/env bash
# Install SLS field app *dev* integration on this machine.
#
# This is NOT a tablet firmware image. It only wires a git checkout so operators
# (or a future appliance) can launch / autostart the Qt viewer cleanly.
#
# What it installs (user-local by default):
#   ~/.local/bin/sls-camera              → wrapper to viewer/run.sh
#   ~/.local/share/applications/sls-camera.desktop
#   ~/.config/autostart/sls-camera.desktop   (unless --no-autostart)
#
# Optional (needs sudo / network):
#   --with-apt-deps      install freenect, portaudio, etc.
#   --with-kinect-access run fix-kinect-access.sh (gspca blacklist + udev)
#
# Usage (from anywhere):
#   ./software/linux/scripts/install-field-app.sh
#   ./software/linux/scripts/install-field-app.sh --no-autostart
#   ./software/linux/scripts/install-field-app.sh --with-apt-deps --with-kinect-access
#
# Undo:
#   ./software/linux/scripts/uninstall-field-app.sh
#
# Later (TODO): clean desktop / strip Lubuntu chrome before a *firmware package*
# install on tablets; external power / sensor packs are separate work.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LINUX_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VIEWER_ROOT="${LINUX_ROOT}/viewer"
RUN_SH="${VIEWER_ROOT}/run.sh"
REPO_ROOT="$(cd "${LINUX_ROOT}/../.." && pwd)"

WITH_AUTOSTART=1
WITH_APT=0
WITH_KINECT=0
DRY_RUN=0

usage() {
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-autostart) WITH_AUTOSTART=0; shift ;;
    --with-autostart) WITH_AUTOSTART=1; shift ;;
    --with-apt-deps) WITH_APT=1; shift ;;
    --with-kinect-access) WITH_KINECT=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY-RUN: $*"
  else
    "$@"
  fi
}

write_file() {
  # write_file <path>  then content on stdin
  local path="$1"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY-RUN: write ${path}"
    cat >/dev/null
    return
  fi
  mkdir -p "$(dirname "$path")"
  cat >"$path"
}

if [[ ! -x "$RUN_SH" && ! -f "$RUN_SH" ]]; then
  echo "ERROR: viewer run.sh not found at ${RUN_SH}" >&2
  exit 1
fi
chmod +x "$RUN_SH" 2>/dev/null || true

echo "=== SLS field app install (dev packaging) ==="
echo "Repo:    ${REPO_ROOT}"
echo "Viewer:  ${VIEWER_ROOT}"
echo "Autostart: $([[ $WITH_AUTOSTART -eq 1 ]] && echo yes || echo no)"
echo

# --- optional host packages ---
if [[ "$WITH_APT" -eq 1 ]]; then
  echo "--- apt deps ---"
  PKGS=(
    freenect libfreenect-bin
    libportaudio2 alsa-utils
    python3 python3-venv python3-pip
  )
  # ffmpeg is optional; imageio-ffmpeg covers mux if missing
  if command -v apt-get >/dev/null 2>&1; then
    run sudo apt-get update
    run sudo apt-get install -y "${PKGS[@]}"
    echo "NOTE: Kinect mic firmware is separate: sudo apt install kinect-audio-setup"
  else
    echo "WARN: apt-get not found; skip --with-apt-deps"
  fi
  echo
fi

# --- kinect access ---
if [[ "$WITH_KINECT" -eq 1 ]]; then
  echo "--- kinect access (gspca / udev) ---"
  if [[ -x "${SCRIPT_DIR}/fix-kinect-access.sh" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      echo "DRY-RUN: ${SCRIPT_DIR}/fix-kinect-access.sh"
    else
      "${SCRIPT_DIR}/fix-kinect-access.sh"
    fi
  else
    echo "WARN: fix-kinect-access.sh missing"
  fi
  echo
fi

# --- user paths ---
BIN_DIR="${HOME}/.local/bin"
APP_DIR="${HOME}/.local/share/applications"
AUTO_DIR="${HOME}/.config/autostart"
WRAPPER="${BIN_DIR}/sls-camera"
DESKTOP_APP="${APP_DIR}/sls-camera.desktop"
DESKTOP_AUTO="${AUTO_DIR}/sls-camera.desktop"

# Marker so uninstall knows we own these files
MARKER_DIR="${HOME}/.local/share/sls-camera"
MARKER="${MARKER_DIR}/install-manifest.txt"

echo "--- launcher wrapper ---"
run mkdir -p "$BIN_DIR"
write_file "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-field-app.sh — points at this git checkout.
set -euo pipefail
export PATH="\${HOME}/.local/bin:\${PATH}"
cd "${VIEWER_ROOT}"
exec "${RUN_SH}" "\$@"
EOF
run chmod +x "$WRAPPER"
echo "  ${WRAPPER}"

echo "--- desktop entry ---"
# Icon optional; no custom icon yet — leave empty for DE default
write_file "$DESKTOP_APP" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=SLS Camera
Comment=Xbox 360 Kinect SLS field app (depth + skeleton)
Exec=${WRAPPER}
Path=${VIEWER_ROOT}
Terminal=false
Categories=AudioVideo;Utility;
StartupNotify=true
X-SLS-Camera-Install=1
EOF
echo "  ${DESKTOP_APP}"

if [[ "$WITH_AUTOSTART" -eq 1 ]]; then
  echo "--- login autostart ---"
  write_file "$DESKTOP_AUTO" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=SLS Camera
Comment=Autostart SLS field app after login (dev / appliance prep)
Exec=${WRAPPER}
Path=${VIEWER_ROOT}
Terminal=false
X-GNOME-Autostart-enabled=true
X-SLS-Camera-Install=1
EOF
  echo "  ${DESKTOP_AUTO}"
else
  echo "--- login autostart skipped (--no-autostart) ---"
  if [[ -f "$DESKTOP_AUTO" ]]; then
    echo "  (existing ${DESKTOP_AUTO} left in place; use uninstall to remove)"
  fi
fi

# --- manifest for uninstall ---
write_file "$MARKER" <<EOF
# Generated by install-field-app.sh on $(date -Iseconds 2>/dev/null || date)
VIEWER_ROOT=${VIEWER_ROOT}
WRAPPER=${WRAPPER}
DESKTOP_APP=${DESKTOP_APP}
DESKTOP_AUTO=${DESKTOP_AUTO}
WITH_AUTOSTART=${WITH_AUTOSTART}
EOF
echo "  manifest: ${MARKER}"

# Ensure viewer venv can be created on first run (do not force network here)
if [[ ! -x "${VIEWER_ROOT}/.venv/bin/python" ]]; then
  echo
  echo "NOTE: viewer venv not built yet. First launch will create it via run.sh"
  echo "      (needs network once for uv/pip + MediaPipe model)."
fi

echo
echo "=== Install complete ==="
echo "Launch:     sls-camera"
echo "  or:       ${WRAPPER}"
echo "  or:       ${RUN_SH}"
if [[ "$WITH_AUTOSTART" -eq 1 ]]; then
  echo "Autostart:  enabled for next graphical login"
  echo "  disable:  ./software/linux/scripts/uninstall-field-app.sh --keep-launcher"
  echo "            or remove ${DESKTOP_AUTO}"
fi
echo "Uninstall:  ./software/linux/scripts/uninstall-field-app.sh"
echo
echo "Still manual (documented, not automated here):"
echo "  - kinect-audio-setup (+ MSI hash recovery if needed)"
echo "  - tablet firmware image, desktop chrome cleanup"
echo "  - external power policy / sensor bridge (future)"
echo "See: software/linux/docs/FIELD-INSTALL.md"
